SET C51INC=D:\Keil\keil_main_file\C51\Inc;D:\Keil\keil_main_file\C51\Inc\Atmel
SET C51LIB=D:\Keil\keil_main_file\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Keil\keil_main_file\C51\BIN\C51.EXE" @".\Objects\Time.__i"
"D:\Keil\keil_main_file\C51\BIN\BL51.EXE" @".\Objects\Time_Project.lnp"
"D:\Keil\keil_main_file\C51\BIN\OH51.EXE" ".\Objects\Time_Project" 
